// <auto-generated />
using System;
using MedicalEngineMicroService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MedicalEngineMicroService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190810120029_AddedDateTimeToVat")]
    partial class AddedDateTimeToVat
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Lookups.FileStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NormalizedDescription")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("Id");

                    b.ToTable("FileStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 581, DateTimeKind.Local).AddTicks(1708),
                            Description = "Successfully uploaded the file",
                            IsDeleted = false,
                            Name = "Uploaded",
                            NormalizedDescription = "SUCCESSFULLYUPLOADEDTHEFILE",
                            NormalizedName = "UPLOADED",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 584, DateTimeKind.Local).AddTicks(5650)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 584, DateTimeKind.Local).AddTicks(6251),
                            Description = "The manager rejected the file",
                            IsDeleted = false,
                            Name = "Rejected",
                            NormalizedDescription = "THEMANAGERREJECTEDTHEFILE",
                            NormalizedName = "REJECTED",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 584, DateTimeKind.Local).AddTicks(6262)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 584, DateTimeKind.Local).AddTicks(6270),
                            Description = "Ready to submit to the Fund",
                            IsDeleted = false,
                            Name = "Approved",
                            NormalizedDescription = "READYTOSUBMITTOTHEFUND",
                            NormalizedName = "APPROVED",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 584, DateTimeKind.Local).AddTicks(6270)
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 584, DateTimeKind.Local).AddTicks(6539),
                            Description = "File successfully submitted to the Fund",
                            IsDeleted = false,
                            Name = "Submitted",
                            NormalizedDescription = "FILESUCCESSFULLYSUBMITTEDTOTHEFUND",
                            NormalizedName = "SUBMITTED",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 584, DateTimeKind.Local).AddTicks(6543)
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 584, DateTimeKind.Local).AddTicks(6547),
                            Description = "Not all invoices were paid",
                            IsDeleted = false,
                            Name = "Partially Paid",
                            NormalizedDescription = "NOTALLINVOICESWEREPAID",
                            NormalizedName = "PARTIALLY PAID",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 584, DateTimeKind.Local).AddTicks(6547)
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 584, DateTimeKind.Local).AddTicks(6551),
                            Description = "All invoices were successfully paid",
                            IsDeleted = false,
                            Name = "Paid",
                            NormalizedDescription = "ALLINVOICESWERESUCCESSFULLYPAID",
                            NormalizedName = "PAID",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 584, DateTimeKind.Local).AddTicks(6551)
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 584, DateTimeKind.Local).AddTicks(6555),
                            Description = "File Overdue",
                            IsDeleted = false,
                            Name = "Overdue",
                            NormalizedDescription = "FILEOVERDUE",
                            NormalizedName = "OVERDUE",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 584, DateTimeKind.Local).AddTicks(6555)
                        });
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Lookups.InvoiceStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NormalizedDescription")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("Id");

                    b.ToTable("InvoiceStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 590, DateTimeKind.Local).AddTicks(7402),
                            Description = "Pending",
                            IsDeleted = false,
                            Name = "Pending",
                            NormalizedDescription = "PENDING",
                            NormalizedName = "PENDING",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 590, DateTimeKind.Local).AddTicks(7425)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 590, DateTimeKind.Local).AddTicks(7475),
                            Description = "Approved",
                            IsDeleted = false,
                            Name = "Approved",
                            NormalizedDescription = "APPROVED",
                            NormalizedName = "APPROVED",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 590, DateTimeKind.Local).AddTicks(7479)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 590, DateTimeKind.Local).AddTicks(7483),
                            Description = "Payment rejected",
                            IsDeleted = false,
                            Name = "Rejected",
                            NormalizedDescription = "PAYMENTREJECTED",
                            NormalizedName = "REJECTED",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 590, DateTimeKind.Local).AddTicks(7483)
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 590, DateTimeKind.Local).AddTicks(7575),
                            Description = "Invoice submitted to the fund",
                            IsDeleted = false,
                            Name = "Submitted",
                            NormalizedDescription = "INVOICESUBMITTEDTOTHEFUND",
                            NormalizedName = "SUBMITTED",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 590, DateTimeKind.Local).AddTicks(7579)
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 590, DateTimeKind.Local).AddTicks(7591),
                            Description = "Invoice paid",
                            IsDeleted = false,
                            Name = "Paid",
                            NormalizedDescription = "INVOICEPAID",
                            NormalizedName = "PAID",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 590, DateTimeKind.Local).AddTicks(7591)
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 590, DateTimeKind.Local).AddTicks(7595),
                            Description = "Invoice Overdue",
                            IsDeleted = false,
                            Name = "Overdue",
                            NormalizedDescription = "INVOICEOVERDUE",
                            NormalizedName = "OVERDUE",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 590, DateTimeKind.Local).AddTicks(7598)
                        });
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Medical.Tariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0");

                    b.Property<int>("MedicalItemId");

                    b.Property<double>("RecommendedUnit");

                    b.Property<int>("TariffUnitCostId");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("DATETIME2");

                    b.HasKey("Id");

                    b.HasIndex("MedicalItemId");

                    b.HasIndex("TariffUnitCostId");

                    b.ToTable("Tariffs");
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Medical.TariffBaseUnitCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("ActualAmount")
                        .HasColumnType("DECIMAL (19, 4)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0");

                    b.Property<string>("Name");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("Id");

                    b.ToTable("TariffBaseUnitCosts");
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Medical.TariffType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NormalizedDescription")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("Id");

                    b.ToTable("TariffTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 595, DateTimeKind.Local).AddTicks(5095),
                            Description = "Coid Tariffs",
                            IsDeleted = false,
                            Name = "Coida",
                            NormalizedDescription = "COIDTARIFFS",
                            NormalizedName = "COIDA",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 595, DateTimeKind.Local).AddTicks(5118)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 595, DateTimeKind.Local).AddTicks(5157),
                            Description = "None Coid Tariffs",
                            IsDeleted = false,
                            Name = "NoneCoid",
                            NormalizedDescription = "NONECOIDTARIFFS",
                            NormalizedName = "NONECOID",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 595, DateTimeKind.Local).AddTicks(5157)
                        });
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Medical.VatType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0");

                    b.Property<double>("Percentage")
                        .HasColumnType("DECIMAL (5, 2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime>("ValidFrom");

                    b.Property<DateTime?>("ValidTo");

                    b.HasKey("Id");

                    b.ToTable("VatTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 601, DateTimeKind.Local).AddTicks(4371),
                            Description = "14% Percent VAT",
                            IsDeleted = false,
                            Percentage = 0.14000000000000001,
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 601, DateTimeKind.Local).AddTicks(4391),
                            ValidFrom = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2018, 3, 31, 23, 59, 59, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 601, DateTimeKind.Local).AddTicks(5657),
                            Description = "15% Percent VAT",
                            IsDeleted = false,
                            Percentage = 0.14999999999999999,
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 601, DateTimeKind.Local).AddTicks(5661),
                            ValidFrom = new DateTime(2018, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Medical.MedicalItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasMaxLength(10);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0");

                    b.Property<int>("MedicalItemTypeId");

                    b.Property<int>("NappiCodeTypeId");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("Id");

                    b.HasIndex("MedicalItemTypeId");

                    b.HasIndex("NappiCodeTypeId");

                    b.ToTable("MedicalItems");
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Medical.MedicalItemPublication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0");

                    b.Property<int>("MedicalItemId");

                    b.Property<string>("Name")
                        .HasMaxLength(255);

                    b.Property<int>("PublicationTypeId");

                    b.Property<double>("Quantity");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("Id");

                    b.HasIndex("PublicationTypeId");

                    b.HasIndex("MedicalItemId", "PublicationTypeId")
                        .IsUnique();

                    b.ToTable("MedicalItemPublications");
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Medical.MedicalItemPublicationPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0");

                    b.Property<int>("MedicalItemPublicationId");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime>("ValiFrom");

                    b.Property<DateTime>("ValidTo");

                    b.HasKey("Id");

                    b.HasIndex("MedicalItemPublicationId");

                    b.ToTable("MedicalItemPublicationPeriods");
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Medical.MedicalItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("NormalizedDescription")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("Id");

                    b.ToTable("MedicalItemTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 613, DateTimeKind.Local).AddTicks(7806),
                            Description = "Unknown",
                            IsDeleted = false,
                            Name = "-",
                            NormalizedDescription = "UNKNOWN",
                            NormalizedName = "-",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 613, DateTimeKind.Local).AddTicks(7829)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 613, DateTimeKind.Local).AddTicks(7876),
                            Description = "Treatment or Procedure Code",
                            IsDeleted = true,
                            Name = "IT",
                            NormalizedDescription = "TREATMENTORPROCEDURECODE",
                            NormalizedName = "IT",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 613, DateTimeKind.Local).AddTicks(7876)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 613, DateTimeKind.Local).AddTicks(7879),
                            Description = "Drug or Pharmaceutical Item (NAPPI)",
                            IsDeleted = true,
                            Name = "ID",
                            NormalizedDescription = "DRUGORPHARMACEUTICALITEM(NAPPI)",
                            NormalizedName = "ID",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 613, DateTimeKind.Local).AddTicks(7879)
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 613, DateTimeKind.Local).AddTicks(7883),
                            Description = "Modifier",
                            IsDeleted = false,
                            Name = "M",
                            NormalizedDescription = "MODIFIER",
                            NormalizedName = "M",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 613, DateTimeKind.Local).AddTicks(7883)
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 613, DateTimeKind.Local).AddTicks(7887),
                            Description = "Rule",
                            IsDeleted = false,
                            Name = "R",
                            NormalizedDescription = "RULE",
                            NormalizedName = "R",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 613, DateTimeKind.Local).AddTicks(7887)
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 613, DateTimeKind.Local).AddTicks(7891),
                            Description = "Note",
                            IsDeleted = false,
                            Name = "N",
                            NormalizedDescription = "NOTE",
                            NormalizedName = "N",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 613, DateTimeKind.Local).AddTicks(7891)
                        });
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Medical.NappiCodeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("DosageFrom");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ManufacturerCode");

                    b.Property<string>("NappiCode");

                    b.Property<string>("ProductName");

                    b.Property<int>("ProductPackSize");

                    b.Property<int>("ProductStrength");

                    b.Property<int>("Schedule");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("NappiCodeTypes");
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Medical.Practitioner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0");

                    b.Property<bool>("IsMedReportRequired");

                    b.Property<double>("MaxTreatmentDays");

                    b.Property<string>("NRPLPracticeCode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NormalizedDescription")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("PracticeCode");

                    b.Property<int>("PractitionerGroupTypeId");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("Id");

                    b.HasIndex("PractitionerGroupTypeId");

                    b.ToTable("Practitioners");
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Medical.PractitionerGroupType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NormalizedDescription")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("Id");

                    b.ToTable("PractitionerGroupTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 636, DateTimeKind.Local).AddTicks(5731),
                            Description = "ALL discipline",
                            IsDeleted = false,
                            Name = "ALL",
                            NormalizedDescription = "ALL DISCIPLINE",
                            NormalizedName = "ALL",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 636, DateTimeKind.Local).AddTicks(5754)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 636, DateTimeKind.Local).AddTicks(5781),
                            Description = "SPC discipline",
                            IsDeleted = false,
                            Name = "SPC",
                            NormalizedDescription = "SPC DISCIPLINE",
                            NormalizedName = "SPC",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 636, DateTimeKind.Local).AddTicks(5781)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 636, DateTimeKind.Local).AddTicks(5785),
                            Description = "GPH discipline",
                            IsDeleted = false,
                            Name = "GPH",
                            NormalizedDescription = "GPH DISCIPLINE",
                            NormalizedName = "GPH",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 636, DateTimeKind.Local).AddTicks(5785)
                        });
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Medical.PractitionerPractitionerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0");

                    b.Property<int>("PractitionerId");

                    b.Property<int>("PractitionerTypeId");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("Id");

                    b.HasIndex("PractitionerId");

                    b.HasIndex("PractitionerTypeId");

                    b.ToTable("PractitionerPractitionerTypes");
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Medical.PractitionerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NormalizedDescription")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("Id");

                    b.ToTable("PractitionerTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 630, DateTimeKind.Local).AddTicks(8078),
                            Description = "Hospital",
                            IsDeleted = false,
                            Name = "Hospital",
                            NormalizedDescription = "HOSPITAL",
                            NormalizedName = "HOSPITAL",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 630, DateTimeKind.Local).AddTicks(8105)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 630, DateTimeKind.Local).AddTicks(8155),
                            Description = "Dentist",
                            IsDeleted = false,
                            Name = "Dentist",
                            NormalizedDescription = "DENTIST",
                            NormalizedName = "DENTIST",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 630, DateTimeKind.Local).AddTicks(8159)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 630, DateTimeKind.Local).AddTicks(8159),
                            Description = "Ambulance",
                            IsDeleted = false,
                            Name = "Ambulance",
                            NormalizedDescription = "AMBULANCE",
                            NormalizedName = "AMBULANCE",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 630, DateTimeKind.Local).AddTicks(8159)
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 630, DateTimeKind.Local).AddTicks(8163),
                            Description = "Specialist",
                            IsDeleted = false,
                            Name = "Specialist",
                            NormalizedDescription = "SPECIALIST",
                            NormalizedName = "SPECIALIST",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 630, DateTimeKind.Local).AddTicks(8163)
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 630, DateTimeKind.Local).AddTicks(8167),
                            Description = "Anaesthetist",
                            IsDeleted = false,
                            Name = "Anaesthetist",
                            NormalizedDescription = "ANAESTHETIST",
                            NormalizedName = "ANAESTHETIST",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 630, DateTimeKind.Local).AddTicks(8167)
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 630, DateTimeKind.Local).AddTicks(8171),
                            Description = "General Practitioner",
                            IsDeleted = false,
                            Name = "GP",
                            NormalizedDescription = "GENERALPRACTITIONER",
                            NormalizedName = "GP",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 630, DateTimeKind.Local).AddTicks(8171)
                        });
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Medical.SectionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NormalizedDescription")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("SectionNo");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("Id");

                    b.ToTable("SectionTypes");
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Medical.TariffBaseUnitCostType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NormalizedDescription")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("Id");

                    b.ToTable("TariffBaseUnitCostTypes");
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Users.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Users.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("PracticeNumber");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Users.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("PublicationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("0");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NormalizedDescription")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("PublicationNo")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("Id");

                    b.ToTable("PublicationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 626, DateTimeKind.Local).AddTicks(4385),
                            Description = "Chiropractor Tariffs",
                            IsDeleted = false,
                            Name = "Chiropractor",
                            NormalizedDescription = "CHIROPRACTORTARIFFS",
                            NormalizedName = "CHIROPRACTOR",
                            PublicationNo = "11111",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 626, DateTimeKind.Local).AddTicks(4404)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 626, DateTimeKind.Local).AddTicks(5070),
                            Description = "Radiologists Tariffs",
                            IsDeleted = false,
                            Name = "Radiologist",
                            NormalizedDescription = "RADIOLOGISTSTARIFFS",
                            NormalizedName = "RADIOLOGIST",
                            PublicationNo = "11111",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 626, DateTimeKind.Local).AddTicks(5074)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 626, DateTimeKind.Local).AddTicks(5082),
                            Description = "Dentists tarrifs",
                            IsDeleted = false,
                            Name = "Dentist",
                            NormalizedDescription = "DENTISTSTARRIFS",
                            NormalizedName = "DENTIST",
                            PublicationNo = "11111",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 626, DateTimeKind.Local).AddTicks(5082)
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 626, DateTimeKind.Local).AddTicks(5086),
                            Description = "Physiotherapist tariffs",
                            IsDeleted = false,
                            Name = "Physiotherapist",
                            NormalizedDescription = "PHYSIOTHERAPISTTARIFFS",
                            NormalizedName = "PHYSIOTHERAPIST",
                            PublicationNo = "11111",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 626, DateTimeKind.Local).AddTicks(5086)
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 626, DateTimeKind.Local).AddTicks(5086),
                            Description = "Private Ambulance Tariffs",
                            IsDeleted = false,
                            Name = "Private Ambulance",
                            NormalizedDescription = "PRIVATEAMBULANCETARIFFS",
                            NormalizedName = "PRIVATEAMBULANCE",
                            PublicationNo = "11111",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 626, DateTimeKind.Local).AddTicks(5090)
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 626, DateTimeKind.Local).AddTicks(5090),
                            Description = "General Practioner Tariffs",
                            IsDeleted = false,
                            Name = "General Practioner",
                            NormalizedDescription = "GENERALPRACTIONERTARIFFS",
                            NormalizedName = "GENERALPRACTIONER",
                            PublicationNo = "11111",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 626, DateTimeKind.Local).AddTicks(5093)
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 626, DateTimeKind.Local).AddTicks(5093),
                            Description = "Renal Care Tariffs",
                            IsDeleted = false,
                            Name = "Renal Care",
                            NormalizedDescription = "RENALCARETARIFFS",
                            NormalizedName = "RENALCARE",
                            PublicationNo = "11111",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 626, DateTimeKind.Local).AddTicks(5093)
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 626, DateTimeKind.Local).AddTicks(5097),
                            Description = "Social Worker Tariffs",
                            IsDeleted = false,
                            Name = "Social Worker",
                            NormalizedDescription = "SOCIALWORKERTARIFFS",
                            NormalizedName = "SOCIALWORKER",
                            PublicationNo = "11111",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 626, DateTimeKind.Local).AddTicks(5097)
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "Administrator",
                            CreatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 626, DateTimeKind.Local).AddTicks(5097),
                            Description = "Wound Care Tariffs",
                            IsDeleted = false,
                            Name = "Wound Care",
                            NormalizedDescription = "WOUNDCARETARIFFS",
                            NormalizedName = "WOUNDCARE",
                            PublicationNo = "11111",
                            UpdatedBy = "Administrator",
                            UpdatedDate = new DateTime(2019, 8, 10, 14, 0, 28, 626, DateTimeKind.Local).AddTicks(5097)
                        });
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Medical.Tariff", b =>
                {
                    b.HasOne("MedicalEngineMicroService.Core.Models.Entities.Medical.MedicalItem", "MedicalItem")
                        .WithMany()
                        .HasForeignKey("MedicalItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MedicalEngineMicroService.Core.Models.Entities.Medical.TariffBaseUnitCost", "TariffUnitCost")
                        .WithMany()
                        .HasForeignKey("TariffUnitCostId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Medical.MedicalItem", b =>
                {
                    b.HasOne("MedicalEngineMicroService.Core.Models.Entities.Medical.MedicalItemType", "MedicalItemType")
                        .WithMany()
                        .HasForeignKey("MedicalItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MedicalEngineMicroService.Core.Models.Entities.Medical.NappiCodeType", "NappiCodeType")
                        .WithMany()
                        .HasForeignKey("NappiCodeTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Medical.MedicalItemPublication", b =>
                {
                    b.HasOne("MedicalEngineMicroService.Core.Models.Entities.Medical.MedicalItem", "MedicalItem")
                        .WithMany()
                        .HasForeignKey("MedicalItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PublicationType", "PublicationType")
                        .WithMany()
                        .HasForeignKey("PublicationTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Medical.MedicalItemPublicationPeriod", b =>
                {
                    b.HasOne("MedicalEngineMicroService.Core.Models.Entities.Medical.MedicalItemPublication", "MedicalItemPublication")
                        .WithMany()
                        .HasForeignKey("MedicalItemPublicationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Medical.Practitioner", b =>
                {
                    b.HasOne("MedicalEngineMicroService.Core.Models.Entities.Medical.PractitionerGroupType", "PractitionerGroupType")
                        .WithMany()
                        .HasForeignKey("PractitionerGroupTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Medical.PractitionerPractitionerType", b =>
                {
                    b.HasOne("MedicalEngineMicroService.Core.Models.Entities.Medical.Practitioner", "Practitioner")
                        .WithMany()
                        .HasForeignKey("PractitionerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MedicalEngineMicroService.Core.Models.Entities.Medical.PractitionerType", "PractitionerType")
                        .WithMany()
                        .HasForeignKey("PractitionerTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MedicalEngineMicroService.Core.Models.Entities.Users.ApplicationUserRole", b =>
                {
                    b.HasOne("MedicalEngineMicroService.Core.Models.Entities.Users.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MedicalEngineMicroService.Core.Models.Entities.Users.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("MedicalEngineMicroService.Core.Models.Entities.Users.ApplicationRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MedicalEngineMicroService.Core.Models.Entities.Users.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MedicalEngineMicroService.Core.Models.Entities.Users.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MedicalEngineMicroService.Core.Models.Entities.Users.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
