using MedicalEngineMicroService.Common.Extensions;
using MedicalEngineMicroService.Core.Models.Entities.Tariffs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MedicalEngineMicroService.Persistence.EntityConfigurations.Tariffs {
    public class MedicalItemPublicationConfiguration : IEntityTypeConfiguration<MedicalItemPublication> {
        public void Configure (EntityTypeBuilder<MedicalItemPublication> builder) {
            builder.ConfigureLookupDescription ();

            builder.HasIndex (medicalItem => new { medicalItem.MedicalItemId, medicalItem.PublicationId })
                .IsUnique (true);

            builder.Property (medicalItem => medicalItem.Description).IsRequired ();

            builder.Property (medicalItem => medicalItem.Quantity).HasDefaultValue (1.00);

            SeedMedicalItemPublication (builder);

        }

        private void SeedMedicalItemPublication (EntityTypeBuilder<MedicalItemPublication> modelBuilder) {
            modelBuilder.HasData (
                new MedicalItemPublication { Id = 1, MedicalItemId = 1, PublicationId = 2, Description = @"Written report on X-rays: The lowest level code for a new patient office (consulting rooms) visit, is applicable only where a radiologist is requested to give a written report on X-rays taken elsewhere and submitted to him. The above mentioned item and the lowest level initial hospital visit code, as appropriate are not to be used for routine reporting of X-rays taken elsewhere", NormalizedDescription = @"WRITTENREPORTONX-RAYS:THELOWESTLEVELCODEFORANEWPATIENTOFFICE(CONSULTINGROOMS)VISIT,ISAPPLICABLEONLYWHEREARADIOLOGISTISREQUESTEDTOGIVEAWRITTENREPORTONX-RAYSTAKENELSEWHEREANDSUBMITTEDTOHIM.THEABOVEMENTIONEDITEMANDTHELOWESTLEVELINITIALHOSPITALVISITCODE,ASAPPROPRIATEARENOTTOBEUSEDFORROUTINEREPORTINGOFX-RAYSTAKENELSEWHERE" },
                new MedicalItemPublication { Id = 2, MedicalItemId = 2, PublicationId = 2, Description = @"Procedures performed in own procedure rooms: Procedures performed in doctors' own procedure rooms instead of in a hospital theatre or unattached theatre unit: as per fee for procedure + 100% (the value of modifier 0004 equals 100% of the value of the procedure performed). See Section V (Section G in SAMA's DBT) for a list of procedures, which are often done in rooms to which Modifier 0004 should not be applied. Please note: Only the medical practitioner who owns the facility and the equipment may charge modifier 0004. Only one person may claim this modifier for procedures performed in doctors' own procedure rooms", NormalizedDescription = @"PROCEDURESPERFORMEDINOWNPROCEDUREROOMS:PROCEDURESPERFORMEDINDOCTORS'OWNPROCEDUREROOMSINSTEADOFINAHOSPITALTHEATREORUNATTACHEDTHEATREUNIT:ASPERFEEFORPROCEDURE+100%(THEVALUEOFMODIFIER0004EQUALS100%OFTHEVALUEOFTHEPROCEDUREPERFORMED).SEESECTIONV(SECTIONGINSAMA'SDBT)FORALISTOFPROCEDURES,WHICHAREOFTENDONEINROOMSTOWHICHMODIFIER0004SHOULDNOTBEAPPLIED.PLEASENOTE:ONLYTHEMEDICALPRACTITIONERWHOOWNSTHEFACILITYANDTHEEQUIPMENTMAYCHARGEMODIFIER0004.ONLYONEPERSONMAYCLAIMTHISMODIFIERFORPROCEDURESPERFORMEDINDOCTORS'OWNPROCEDUREROOMS" },
                new MedicalItemPublication {
                    Id = 3, MedicalItemId = 3, PublicationId = 2, Description = @"Multiple therapeutic procedures/operations under the same anaesthetic:\r\na) Unless otherwise identified in the tariff when multiple therapeutic procedures/operations add significant time and/or complexity, and when each procedure/operation is clearly identified and defined, the following values shall prevail:  100% (full value) for the first or major procedure/operation, 75% for the second procedure/operation, 50% for the third procedure/operation, 25% for the fourth and subsequent procedures/operations. This modifier does not apply to purely diagnostic procedures.\r\nb) In the case of multiple fractures and/or dislocations the above values shall prevail.\r\nc) When purely diagnostic endoscopic procedures or diagnostic endoscopic procedures unrelated to any therapeutic procedures performed, are performed under the same general anaesthetic, Modifier 0005 is not applicable to the fees for such diagnostic endoscopic procedures as the fees for endoscopic procedures do not provide for after-care. Specify unrelated endoscopic procedure and provide diagnosis to indicate diagnostic endoscopic procedure(s) unrelated to other (therapeutic) procedures performed under the same anaesthetic.\r\nd) Please note:  When more than one small procedure is performed and the tariff makes provision for items for ""subsequent"" or ""maximum for multiple additional procedures"" (see Section 2. Integumentary System) Modifier 0005 is not applicable as the fee is already a reduced fee.\r\ne) ?+? Means that this item is used in addition to another definitive procedure and is therefore not subject to reduction according to Modifier 0005 (see also Modifier 0082)", NormalizedDescription = @"
                    MULTIPLETHERAPEUTICPROCEDURES / OPERATIONSUNDERTHESAMEANAESTHETIC: \R\ NA) UNLESSOTHERWISEIDENTIFIEDINTHETARIFFWHENMULTIPLETHERAPEUTICPROCEDURES / OPERATIONSADDSIGNIFICANTTIMEAND / ORCOMPLEXITY, ANDWHENEACHPROCEDURE / OPERATIONISCLEARLYIDENTIFIEDANDDEFINED, THEFOLLOWINGVALUESSHALLPREVAIL : 100 % (FULLVALUE) FORTHEFIRSTORMAJORPROCEDURE / OPERATION, 75 % FORTHESECONDPROCEDURE / OPERATION, 50 % FORTHETHIRDPROCEDURE / OPERATION, 25 % FORTHEFOURTHANDSUBSEQUENTPROCEDURES / OPERATIONS.THISMODIFIERDOESNOTAPPLYTOPURELYDIAGNOSTICPROCEDURES.\R\ NB) INTHECASEOFMULTIPLEFRACTURESAND / ORDISLOCATIONSTHEABOVEVALUESSHALLPREVAIL.\R\ NC) WHENPURELYDIAGNOSTICENDOSCOPICPROCEDURESORDIAGNOSTICENDOSCOPICPROCEDURESUNRELATEDTOANYTHERAPEUTICPROCEDURESPERFORMED,
        AREPERFORMEDUNDERTHESAMEGENERALANAESTHETIC,
        MODIFIER0005ISNOTAPPLICABLETOTHEFEESFORSUCHDIAGNOSTICENDOSCOPICPROCEDURESASTHEFEESFORENDOSCOPICPROCEDURESDONOTPROVIDEFORAFTER - CARE.SPECIFYUNRELATEDENDOSCOPICPROCEDUREANDPROVIDEDIAGNOSISTOINDICATEDIAGNOSTICENDOSCOPICPROCEDURE (S) UNRELATEDTOOTHER (THERAPEUTIC) PROCEDURESPERFORMEDUNDERTHESAMEANAESTHETIC.\R\ ND) PLEASENOTE : WHENMORETHANONESMALLPROCEDUREISPERFORMEDANDTHETARIFFMAKESPROVISIONFORITEMSFOR ""
    SUBSEQUENT ""
    OR ""
    MAXIMUMFORMULTIPLEADDITIONALPROCEDURES "" (SEESECTION2.INTEGUMENTARYSYSTEM) MODIFIER0005ISNOTAPPLICABLEASTHEFEEISALREADYAREDUCEDFEE.\R\ NE) ? + ? MEANSTHATTHISITEMISUSEDINADDITIONTOANOTHERDEFINITIVEPROCEDUREANDISTHEREFORENOTSUBJECTTOREDUCTIONACCORDINGTOMODIFIER0005 (SEEALSOMODIFIER0082)
"
                },
                new MedicalItemPublication { Id = 4, MedicalItemId = 4, PublicationId = 2, Description = @"Visiting specialists performing procedures:  Where specialists visit smaller centres to perform procedures, fees for these particular procedures are exclusive of after-care. The referring practitioner will then be entitled to subsequent hospital visits for after-care. If the referring practitioner is not available, the specialist shall, on consultation with the patient, choose an appropriate locum tenens. Both the surgeon and the practitioner who handled the after-care, must in such instances quote Modifier 0006 with the particular items which they use", NormalizedDescription = @"VISITINGSPECIALISTSPERFORMINGPROCEDURES:WHERESPECIALISTSVISITSMALLERCENTRESTOPERFORMPROCEDURES,FEESFORTHESEPARTICULARPROCEDURESAREEXCLUSIVEOFAFTER-CARE.THEREFERRINGPRACTITIONERWILLTHENBEENTITLEDTOSUBSEQUENTHOSPITALVISITSFORAFTER-CARE.IFTHEREFERRINGPRACTITIONERISNOTAVAILABLE,THESPECIALISTSHALL,ONCONSULTATIONWITHTHEPATIENT,CHOOSEANAPPROPRIATELOCUMTENENS.BOTHTHESURGEONANDTHEPRACTITIONERWHOHANDLEDTHEAFTER-CARE,MUSTINSUCHINSTANCESQUOTEMODIFIER0006WITHTHEPARTICULARITEMSWHICHTHEYUSE" },
                new MedicalItemPublication { Id = 5, MedicalItemId = 5, PublicationId = 2, Description = @"a) Use of own monitoring equipment in the rooms:  Remuneration for the use of any type of own monitoring equipment in the rooms for procedures performed under intravenous sedation - 15,00 clinical procedure units irrespective of the number of items of equipment provided.\r\nb) Use of own equipment in hospital theatre or unattached theatre unit:  Remuneration for the use of any type of own equipment for procedures performed in a hospital theatre or unattached theatre unit when appropriate equipment is not provided by the hospital - 15,00 clinical procedure units irrespective of the number of items of equipment provided.", NormalizedDescription = @"
    A) USEOFOWNMONITORINGEQUIPMENTINTHEROOMS : REMUNERATIONFORTHEUSEOFANYTYPEOFOWNMONITORINGEQUIPMENTINTHEROOMSFORPROCEDURESPERFORMEDUNDERINTRAVENOUSSEDATION - 15, 00 CLINICALPROCEDUREUNITSIRRESPECTIVEOFTHENUMBEROFITEMSOFEQUIPMENTPROVIDED.\R\ NB) USEOFOWNEQUIPMENTINHOSPITALTHEATREORUNATTACHEDTHEATREUNIT : REMUNERATIONFORTHEUSEOFANYTYPEOFOWNEQUIPMENTFORPROCEDURESPERFORMEDINAHOSPITALTHEATREORUNATTACHEDTHEATREUNITWHENAPPROPRIATEEQUIPMENTISNOTPROVIDEDBYTHEHOSPITAL - 15, 00 CLINICALPROCEDUREUNITSIRRESPECTIVEOFTHENUMBEROFITEMSOFEQUIPMENTPROVIDED.
" },
                new MedicalItemPublication { Id = 6, MedicalItemId = 6, PublicationId = 2, Description = @"Specialist surgeon assistant: Where a procedure requires a registered specialist surgeon assistant, the fee is 33,33% (1/3) of the fee for the specialist surgeon", NormalizedDescription = @"SPECIALISTSURGEONASSISTANT:WHEREAPROCEDUREREQUIRESAREGISTEREDSPECIALISTSURGEONASSISTANT,THEFEEIS33,33%(1/3)OFTHEFEEFORTHESPECIALISTSURGEON" },
                new MedicalItemPublication { Id = 7, MedicalItemId = 7, PublicationId = 2, Description = @"Assistant: The fee for an assistant is 20% of the fee for the specialist surgeon, with a minimum of 36,00 clinical procedure units. The minimum fee payable may not be less than 36,00 clinical procedures units", NormalizedDescription = @"ASSISTANT:THEFEEFORANASSISTANTIS20%OFTHEFEEFORTHESPECIALISTSURGEON,WITHAMINIMUMOF36,00CLINICALPROCEDUREUNITS.THEMINIMUMFEEPAYABLEMAYNOTBELESSTHAN36,00CLINICALPROCEDURESUNITS" },
                new MedicalItemPublication { Id = 8, MedicalItemId = 8, PublicationId = 2, Description = @"Local anaesthetic: (a) A fee for a local anaesthetic administered by the operator may only be charged for (1) an operation or procedure having a value greater than 30,00 clinical procedure units (i.e. 31,00 or more clinical procedure units allocated to a single item) or (2) where more than one operation or procedure is done at the same time with a combined value greater than 50,00 clinical procedure units. (b) The fee shall be calculated according to the basic anaesthetic units for the specific operation. Anaesthetic time may not be charged for, but the minimum fee as per Modifier 0036: Anaesthetic administered by a general practitioner, shall be applicable in such a case. (c) Not applicable to radiological procedures (such as angiography and myelography. (d) No fee may be levied for topical application of local anaesthetic. (e) Please note: Modifier 0010: Local anaesthetic administered by the operator, may not be added on the surgeon?s account for procedures that were performed under general anaesthetic.", NormalizedDescription = @"LOCALANAESTHETIC:(A)AFEEFORALOCALANAESTHETICADMINISTEREDBYTHEOPERATORMAYONLYBECHARGEDFOR(1)ANOPERATIONORPROCEDUREHAVINGAVALUEGREATERTHAN30,00CLINICALPROCEDUREUNITS(I.E.31,00ORMORECLINICALPROCEDUREUNITSALLOCATEDTOASINGLEITEM)OR(2)WHEREMORETHANONEOPERATIONORPROCEDUREISDONEATTHESAMETIMEWITHACOMBINEDVALUEGREATERTHAN50,00CLINICALPROCEDUREUNITS.(B)THEFEESHALLBECALCULATEDACCORDINGTOTHEBASICANAESTHETICUNITSFORTHESPECIFICOPERATION.ANAESTHETICTIMEMAYNOTBECHARGEDFOR,BUTTHEMINIMUMFEEASPERMODIFIER0036:ANAESTHETICADMINISTEREDBYAGENERALPRACTITIONER,SHALLBEAPPLICABLEINSUCHACASE.(C)NOTAPPLICABLETORADIOLOGICALPROCEDURES(SUCHASANGIOGRAPHYANDMYELOGRAPHY.(D)NOFEEMAYBELEVIEDFORTOPICALAPPLICATIONOFLOCALANAESTHETIC.(E)PLEASENOTE:MODIFIER0010:LOCALANAESTHETICADMINISTEREDBYTHEOPERATOR,MAYNOTBEADDEDONTHESURGEON?SACCOUNTFORPROCEDURESTHATWEREPERFORMEDUNDERGENERALANAESTHETIC." },
                new MedicalItemPublication { Id = 9, MedicalItemId = 9, PublicationId = 2, Description = @"Emergency procedures: Any bona fide, justifiable emergency procedure (all hours) undertaken in an operating theatre and/or in another setting in lieu of an operating theatre, will attract an additional 12,00 clinical procedure units per half-hour or part thereof of the operating time for all members of the surgical team. Modifier 0011 does not apply in respect of patients on scheduled lists. (A medical emergency is any condition where death or irreparable harm to the patient will result if there are undue delays in receiving appropriate medical treatment)", NormalizedDescription = @"EMERGENCYPROCEDURES:ANYBONAFIDE,JUSTIFIABLEEMERGENCYPROCEDURE(ALLHOURS)UNDERTAKENINANOPERATINGTHEATREAND/ORINANOTHERSETTINGINLIEUOFANOPERATINGTHEATRE,WILLATTRACTANADDITIONAL12,00CLINICALPROCEDUREUNITSPERHALF-HOURORPARTTHEREOFOFTHEOPERATINGTIMEFORALLMEMBERSOFTHESURGICALTEAM.MODIFIER0011DOESNOTAPPLYINRESPECTOFPATIENTSONSCHEDULEDLISTS.(AMEDICALEMERGENCYISANYCONDITIONWHEREDEATHORIRREPARABLEHARMTOTHEPATIENTWILLRESULTIFTHEREAREUNDUEDELAYSINRECEIVINGAPPROPRIATEMEDICALTREATMENT)" },
                new MedicalItemPublication { Id = 10, MedicalItemId = 10, PublicationId = 2, Description = @"Endoscopic examinations done at operations: Where a related endoscopic examination is done at an operation by the operating surgeon or the attending anaesthesiologist, only 50% of the fee for the endoscopic examination may be charged", NormalizedDescription = @"ENDOSCOPICEXAMINATIONSDONEATOPERATIONS:WHEREARELATEDENDOSCOPICEXAMINATIONISDONEATANOPERATIONBYTHEOPERATINGSURGEONORTHEATTENDINGANAESTHESIOLOGIST,ONLY50%OFTHEFEEFORTHEENDOSCOPICEXAMINATIONMAYBECHARGED" },
                new MedicalItemPublication { Id = 11, MedicalItemId = 11, PublicationId = 2, Description = @"Operations previously performed by other surgeons: Where an operation is performed which has been previously performed by another surgeon, e.g. a revision or repeat operation, the fee shall be calculated according to the tariff for the full operation plus an additional fee to be negotiated under general Rule J: In exceptional cases where the fee is disproportionately low in relation to actual service rendered, except where already specified in the tariff", NormalizedDescription = @"OPERATIONSPREVIOUSLYPERFORMEDBYOTHERSURGEONS:WHEREANOPERATIONISPERFORMEDWHICHHASBEENPREVIOUSLYPERFORMEDBYANOTHERSURGEON,E.G.AREVISIONORREPEATOPERATION,THEFEESHALLBECALCULATEDACCORDINGTOTHETARIFFFORTHEFULLOPERATIONPLUSANADDITIONALFEETOBENEGOTIATEDUNDERGENERALRULEJ:INEXCEPTIONALCASESWHERETHEFEEISDISPROPORTIONATELYLOWINRELATIONTOACTUALSERVICERENDERED,EXCEPTWHEREALREADYSPECIFIEDINTHETARIFF" },
                new MedicalItemPublication { Id = 12, MedicalItemId = 12, PublicationId = 2, Description = @"Intravenous infusions: Where intravenous infusions (including blood and blood cellular products) are administered as part of the after-treatment after the operation or confinement, no extra fees shall be charged as this is included in the global operative or maternity fees.  Should the practitioner doing the operation or attending to the maternity case prefer to ask another practitioner to perform post-operative or post-confinement intravenous infusions, then the practitioner himself (and not the patient) shall be responsible for remunerating such practitioner for the infusions", NormalizedDescription = @"INTRAVENOUSINFUSIONS:WHEREINTRAVENOUSINFUSIONS(INCLUDINGBLOODANDBLOODCELLULARPRODUCTS)AREADMINISTEREDASPARTOFTHEAFTER-TREATMENTAFTERTHEOPERATIONORCONFINEMENT,NOEXTRAFEESSHALLBECHARGEDASTHISISINCLUDEDINTHEGLOBALOPERATIVEORMATERNITYFEES.SHOULDTHEPRACTITIONERDOINGTHEOPERATIONORATTENDINGTOTHEMATERNITYCASEPREFERTOASKANOTHERPRACTITIONERTOPERFORMPOST-OPERATIVEORPOST-CONFINEMENTINTRAVENOUSINFUSIONS,THENTHEPRACTITIONERHIMSELF(ANDNOTTHEPATIENT)SHALLBERESPONSIBLEFORREMUNERATINGSUCHPRACTITIONERFORTHEINFUSIONS" },
                new MedicalItemPublication { Id = 13, MedicalItemId = 13, PublicationId = 2, Description = @"Injections administered by practitioners: When desensitisation, intravenous, intramuscular or subcutaneous injections are administered by the practitioner him-/herself to patients who attend the consulting rooms, a first injection forms part of the consultation/visit and only all subsequent injections for the same condition should be charged at 7.50 consultative services units using modifier 0017 to reflect the amount (not chargeable together with a consultation item)", NormalizedDescription = @"INJECTIONSADMINISTEREDBYPRACTITIONERS:WHENDESENSITISATION,INTRAVENOUS,INTRAMUSCULARORSUBCUTANEOUSINJECTIONSAREADMINISTEREDBYTHEPRACTITIONERHIM-/HERSELFTOPATIENTSWHOATTENDTHECONSULTINGROOMS,AFIRSTINJECTIONFORMSPARTOFTHECONSULTATION/VISITANDONLYALLSUBSEQUENTINJECTIONSFORTHESAMECONDITIONSHOULDBECHARGEDAT7.50CONSULTATIVESERVICESUNITSUSINGMODIFIER0017TOREFLECTTHEAMOUNT(NOTCHARGEABLETOGETHERWITHACONSULTATIONITEM)" },
                new MedicalItemPublication { Id = 14, MedicalItemId = 14, PublicationId = 2, Description = @"Surgical modifier for persons with a BMI of 35> (calculated according to kg/m2): Fee for procedure +50% for surgeons and a 50% increase in anaesthetic time units for anaesthesiologists", NormalizedDescription = @"SURGICALMODIFIERFORPERSONSWITHABMIOF35>(CALCULATEDACCORDINGTOKG/M2):FEEFORPROCEDURE+50%FORSURGEONSANDA50%INCREASEINANAESTHETICTIMEUNITSFORANAESTHESIOLOGISTS" },
                new MedicalItemPublication { Id = 15, MedicalItemId = 15, PublicationId = 2, Description = @"Surgery on neonates (up to and including 28 days after birth) and low birth weight infants (less than 2500g) under general anaesthesia (excluding circumcision): per fee for procedure + 50% for surgeons and a 50% increase in anaesthetic time units for anaesthesiologists", NormalizedDescription = @"SURGERYONNEONATES(UPTOANDINCLUDING28DAYSAFTERBIRTH)ANDLOWBIRTHWEIGHTINFANTS(LESSTHAN2500G)UNDERGENERALANAESTHESIA(EXCLUDINGCIRCUMCISION):PERFEEFORPROCEDURE+50%FORSURGEONSANDA50%INCREASEINANAESTHETICTIMEUNITSFORANAESTHESIOLOGISTS" },
                new MedicalItemPublication { Id = 16, MedicalItemId = 16, PublicationId = 2, Description = @"Where in the treatment of a specific fracture or dislocation (compound or closed) an initial procedure is followed within one month by an open reduction, internal fixation, external skeletal fixation or bone grafting on the same bone, the fee for the initial treatment of that fracture or dislocation shall be reduced by 50%.   Please note:  This reduction does not include the assistant?s fee where applicable.  After one month, a full fee as for the initial treatment, is applicable", NormalizedDescription = @"WHEREINTHETREATMENTOFASPECIFICFRACTUREORDISLOCATION(COMPOUNDORCLOSED)ANINITIALPROCEDUREISFOLLOWEDWITHINONEMONTHBYANOPENREDUCTION,INTERNALFIXATION,EXTERNALSKELETALFIXATIONORBONEGRAFTINGONTHESAMEBONE,THEFEEFORTHEINITIALTREATMENTOFTHATFRACTUREORDISLOCATIONSHALLBEREDUCEDBY50%.PLEASENOTE:THISREDUCTIONDOESNOTINCLUDETHEASSISTANT?SFEEWHEREAPPLICABLE.AFTERONEMONTH,AFULLFEEASFORTHEINITIALTREATMENT,ISAPPLICABLE" },
                new MedicalItemPublication { Id = 17, MedicalItemId = 17, PublicationId = 2, Description = @"A fracture NOT requiring reduction shall be charged on a fee per service basis", NormalizedDescription = @"AFRACTURENOTREQUIRINGREDUCTIONSHALLBECHARGEDONAFEEPERSERVICEBASIS" },
                new MedicalItemPublication { Id = 18, MedicalItemId = 18, PublicationId = 2, Description = @"Where in the treatment of a fracture or dislocation, an initial closed reduction is followed within one month by further closed reductions under general anaesthesia, the fee for such subsequent reductions will be 27,00 clinical procedure units (not including after-care)", NormalizedDescription = @"WHEREINTHETREATMENTOFAFRACTUREORDISLOCATION,ANINITIALCLOSEDREDUCTIONISFOLLOWEDWITHINONEMONTHBYFURTHERCLOSEDREDUCTIONSUNDERGENERALANAESTHESIA,THEFEEFORSUCHSUBSEQUENTREDUCTIONSWILLBE27,00CLINICALPROCEDUREUNITS(NOTINCLUDINGAFTER-CARE)" },
                new MedicalItemPublication { Id = 19, MedicalItemId = 19, PublicationId = 2, Description = @"Except where otherwise specified, in cases of compound fractures, 77,00 clinical procedure units (specialists) and 77,00 clinical procedure units (general practitioners) are to be added to the units for the fractures including debridement", NormalizedDescription = @"EXCEPTWHEREOTHERWISESPECIFIED,INCASESOFCOMPOUNDFRACTURES,77,00CLINICALPROCEDUREUNITS(SPECIALISTS)AND77,00CLINICALPROCEDUREUNITS(GENERALPRACTITIONERS)ARETOBEADDEDTOTHEUNITSFORTHEFRACTURESINCLUDINGDEBRIDEMENT" },
                new MedicalItemPublication { Id = 20, MedicalItemId = 20, PublicationId = 2, Description = @"In cases of a compound fracture where a debridement is followed by internal fixation (excluding fixation with Kirschner wires, as well as  fractures of hands and feet), the full amount according to either Modifier 0049:  Cases of compound fractures, or Modifier 0051:  Fractures requiring open reduction, internal fixation, external skeletal fixation and/or bone grafting, may be added to the fee for the procedure involved, plus half of the amount according to the second modifier (either Modifier 0049: Cases of compound fractures or Modifier 0051: Fractures requiring open reduction, internal fixation, external skeletal fixation and/or bone grafting, as applicable) ", NormalizedDescription = @"INCASESOFACOMPOUNDFRACTUREWHEREADEBRIDEMENTISFOLLOWEDBYINTERNALFIXATION(EXCLUDINGFIXATIONWITHKIRSCHNERWIRES,ASWELLASFRACTURESOFHANDSANDFEET),THEFULLAMOUNTACCORDINGTOEITHERMODIFIER0049:CASESOFCOMPOUNDFRACTURES,ORMODIFIER0051:FRACTURESREQUIRINGOPENREDUCTION,INTERNALFIXATION,EXTERNALSKELETALFIXATIONAND/ORBONEGRAFTING,MAYBEADDEDTOTHEFEEFORTHEPROCEDUREINVOLVED,PLUSHALFOFTHEAMOUNTACCORDINGTOTHESECONDMODIFIER(EITHERMODIFIER0049:CASESOFCOMPOUNDFRACTURESORMODIFIER0051:FRACTURESREQUIRINGOPENREDUCTION,INTERNALFIXATION,EXTERNALSKELETALFIXATIONAND/ORBONEGRAFTING,ASAPPLICABLE)" },
                new MedicalItemPublication { Id = 21, MedicalItemId = 21, PublicationId = 2, Description = @"Fractures requiring open reduction, internal fixation, external skeletal fixation and/or bone grafting: Specialists add 77,00 clinical procedure units. General practitioners add 77,00 clinical procedure units", NormalizedDescription = @"FRACTURESREQUIRINGOPENREDUCTION,INTERNALFIXATION,EXTERNALSKELETALFIXATIONAND/ORBONEGRAFTING:SPECIALISTSADD77,00CLINICALPROCEDUREUNITS.GENERALPRACTITIONERSADD77,00CLINICALPROCEDUREUNITS" },
                new MedicalItemPublication { Id = 22, MedicalItemId = 22, PublicationId = 2, Description = @"Fracture requiring percutaneous internal fixation [insertion and removal of fixatives (wires) in respect of fingers and toes included]: Specialists and general practitioners add 32,00 clinical procedure units", NormalizedDescription = @"FRACTUREREQUIRINGPERCUTANEOUSINTERNALFIXATION[INSERTIONANDREMOVALOFFIXATIVES(WIRES)INRESPECTOFFINGERSANDTOESINCLUDED]:SPECIALISTSANDGENERALPRACTITIONERSADD32,00CLINICALPROCEDUREUNITS" },
                new MedicalItemPublication { Id = 23, MedicalItemId = 23, PublicationId = 2, Description = @"Dislocation requiring open reduction: Units for the specific joint plus 77,00 clinical procedure units for specialists. General practitioners add 77,00 clinical procedure units", NormalizedDescription = @"DISLOCATIONREQUIRINGOPENREDUCTION:UNITSFORTHESPECIFICJOINTPLUS77,00CLINICALPROCEDUREUNITSFORSPECIALISTS.GENERALPRACTITIONERSADD77,00CLINICALPROCEDUREUNITS" },
                new MedicalItemPublication { Id = 24, MedicalItemId = 24, PublicationId = 2, Description = @"Multiple procedures on feet: In multiple procedures on feet, fees for the first foot are calculated according to Modifier 0005: Multiple procedures/operations under the same anaesthetic. Calculate fees for the second foot in the same way, reduce the total to 75% and add to the total for the first foot", NormalizedDescription = @"MULTIPLEPROCEDURESONFEET:INMULTIPLEPROCEDURESONFEET,FEESFORTHEFIRSTFOOTARECALCULATEDACCORDINGTOMODIFIER0005:MULTIPLEPROCEDURES/OPERATIONSUNDERTHESAMEANAESTHETIC.CALCULATEFEESFORTHESECONDFOOTINTHESAMEWAY,REDUCETHETOTALTO75%ANDADDTOTHETOTALFORTHEFIRSTFOOT" },
                new MedicalItemPublication { Id = 25, MedicalItemId = 25, PublicationId = 2, Description = @"Revision operation for total joint replacement and immediate re-substitution (infected or non-infected): per fee for total joint replacement + 100%", NormalizedDescription = @"REVISIONOPERATIONFORTOTALJOINTREPLACEMENTANDIMMEDIATERE-SUBSTITUTION(INFECTEDORNON-INFECTED):PERFEEFORTOTALJOINTREPLACEMENT+100%" },
                new MedicalItemPublication { Id = 26, MedicalItemId = 26, PublicationId = 2, Description = @"Combined procedures on the spine: In cases of combined procedures on the spine, both the orthopaedic surgeon and the neurosurgeon are entitled to the full fee for the relevant part of the operation performed", NormalizedDescription = @"COMBINEDPROCEDURESONTHESPINE:INCASESOFCOMBINEDPROCEDURESONTHESPINE,BOTHTHEORTHOPAEDICSURGEONANDTHENEUROSURGEONAREENTITLEDTOTHEFULLFEEFORTHERELEVANTPARTOFTHEOPERATIONPERFORMED" },
                new MedicalItemPublication { Id = 27, MedicalItemId = 27, PublicationId = 2, Description = @"Where two specialists work together on a replantation procedure, each shall be entitled to two-thirds of the fee for the procedure", NormalizedDescription = @"WHERETWOSPECIALISTSWORKTOGETHERONAREPLANTATIONPROCEDURE,EACHSHALLBEENTITLEDTOTWO-THIRDSOFTHEFEEFORTHEPROCEDURE" },
                new MedicalItemPublication { Id = 28, MedicalItemId = 28, PublicationId = 2, Description = @"Where the replantation is unsuccessful, no further surgical fee is payable for amputation of the non-viable parts", NormalizedDescription = @"WHERETHEREPLANTATIONISUNSUCCESSFUL,NOFURTHERSURGICALFEEISPAYABLEFORAMPUTATIONOFTHENON-VIABLEPARTS" },
                new MedicalItemPublication { Id = 29, MedicalItemId = 29, PublicationId = 2, Description = @"Additional operative procedures by same surgeon, under section 3.8.6: Spinal deformities, within a period of 12 months: 75% of scheduled fee for the lesser procedure, except where otherwise specified elsewhere", NormalizedDescription = @"ADDITIONALOPERATIVEPROCEDURESBYSAMESURGEON,UNDERSECTION3.8.6:SPINALDEFORMITIES,WITHINAPERIODOF12MONTHS:75%OFSCHEDULEDFEEFORTHELESSERPROCEDURE,EXCEPTWHEREOTHERWISESPECIFIEDELSEWHERE" },
                new MedicalItemPublication { Id = 30, MedicalItemId = 30, PublicationId = 2, Description = @"Microsurgery of the fallopian-tubes and ovaries: Where micro-surgical techniques are used, with the aid of a microscope, 25% may be added to the fee", NormalizedDescription = @"MICROSURGERYOFTHEFALLOPIAN-TUBESANDOVARIES:WHEREMICRO-SURGICALTECHNIQUESAREUSED,WITHTHEAIDOFAMICROSCOPE,25%MAYBEADDEDTOTHEFEE" },
                new MedicalItemPublication { Id = 31, MedicalItemId = 31, PublicationId = 2, Description = @"Microsurgery of the larynx: Add 25% to the fee of the operation performed (for other operations requiring the use of an operation microscope, the fee include the use of the microscope, except where otherwise specified elsewhere in the Tariff)", NormalizedDescription = @"MICROSURGERYOFTHELARYNX:ADD25%TOTHEFEEOFTHEOPERATIONPERFORMED(FOROTHEROPERATIONSREQUIRINGTHEUSEOFANOPERATIONMICROSCOPE,THEFEEINCLUDETHEUSEOFTHEMICROSCOPE,EXCEPTWHEREOTHERWISESPECIFIEDELSEWHEREINTHETARIFF)" },
                new MedicalItemPublication { Id = 32, MedicalItemId = 32, PublicationId = 2, Description = @"When endoscopic instruments are used during intranasal surgery: Add 10% of the fee of the procedure performed. Only applicable to items 1025, 1027, 1030, 1033, 1035, 1036, 1039, 1047, 1054 and 1083", NormalizedDescription = @"WHENENDOSCOPICINSTRUMENTSAREUSEDDURINGINTRANASALSURGERY:ADD10%OFTHEFEEOFTHEPROCEDUREPERFORMED.ONLYAPPLICABLETOITEMS1025,1027,1030,1033,1035,1036,1039,1047,1054AND1083" },
                new MedicalItemPublication { Id = 33, MedicalItemId = 33, PublicationId = 2, Description = @"Add 45,00 clinical procedure units to procedure(s) performed through a thorascope", NormalizedDescription = @"ADD45,00CLINICALPROCEDUREUNITSTOPROCEDURE(S)PERFORMEDTHROUGHATHORASCOPE" },
                new MedicalItemPublication { Id = 34, MedicalItemId = 34, PublicationId = 2, Description = @"Non invasive peripheral vascular tests: The number of tests in a single case is restricted to two (2) per diagnosis. Tests are not justified in cases of uncomplicated varicose veins", NormalizedDescription = @"NONINVASIVEPERIPHERALVASCULARTESTS:THENUMBEROFTESTSINASINGLECASEISRESTRICTEDTOTWO(2)PERDIAGNOSIS.TESTSARENOTJUSTIFIEDINCASESOFUNCOMPLICATEDVARICOSEVEINS" },
                new MedicalItemPublication { Id = 35, MedicalItemId = 35, PublicationId = 2, Description = @"When item 1288 (Cardiac catheterisation for congenital heart disease: All ages above 1 year old) or item 1289 (Paediatric cardiac catheterisation: Infants below the age of one year) is performed by paediatric cardiologists (?33?): fee for procedure + 100%", NormalizedDescription = @"WHENITEM1288(CARDIACCATHETERISATIONFORCONGENITALHEARTDISEASE:ALLAGESABOVE1YEAROLD)ORITEM1289(PAEDIATRICCARDIACCATHETERISATION:INFANTSBELOWTHEAGEOFONEYEAR)ISPERFORMEDBYPAEDIATRICCARDIOLOGISTS(?33?):FEEFORPROCEDURE+100%" },
                new MedicalItemPublication { Id = 36, MedicalItemId = 36, PublicationId = 2, Description = @"Endoscopic procedures performed with own equipment : The basic procedure fee plus 33.33 % (1 / 3) of that fee ("" + ""codes excluded) will apply where endoscopic procedures are performed with own equipment.", NormalizedDescription = @"ENDOSCOPICPROCEDURESPERFORMEDWITHOWNEQUIPMENT : THEBASICPROCEDUREFEEPLUS33 .33 % (1 / 3) OFTHATFEE ("" + ""CODESEXCLUDED) WILLAPPLYWHEREENDOSCOPICPROCEDURESAREPERFORMEDWITHOWNEQUIPMENT.
    " },
                new MedicalItemPublication { Id = 37, MedicalItemId = 37, PublicationId = 2, Description = @"Endoscopic procedures performed in own procedure room: The fee plus 21,00 clinical procedure units will apply where endoscopic procedures are performed in rooms with own equipment. This fee is chargeable by medical practitioners who own or rent the facility. Please note: Modifier 0075 is not applicable to any of the items for diagnostic procedures in the otorhinolaryngology sections of the tariff.", NormalizedDescription = @"ENDOSCOPICPROCEDURESPERFORMEDINOWNPROCEDUREROOM:THEFEEPLUS21,00CLINICALPROCEDUREUNITSWILLAPPLYWHEREENDOSCOPICPROCEDURESAREPERFORMEDINROOMSWITHOWNEQUIPMENT.THISFEEISCHARGEABLEBYMEDICALPRACTITIONERSWHOOWNORRENTTHEFACILITY.PLEASENOTE:MODIFIER0075ISNOTAPPLICABLETOANYOFTHEITEMSFORDIAGNOSTICPROCEDURESINTHEOTORHINOLARYNGOLOGYSECTIONSOFTHETARIFF." },
                new MedicalItemPublication { Id = 38, MedicalItemId = 38, PublicationId = 2, Description = @"Physical treatment: When two separate areas are treated simultaneously for totally different conditions, such treatment shall be regarded as two treatments for which separate fees may be charged. (Only applicable if services are provided by a specialist in physical medicine)", NormalizedDescription = @"PHYSICALTREATMENT:WHENTWOSEPARATEAREASARETREATEDSIMULTANEOUSLYFORTOTALLYDIFFERENTCONDITIONS,SUCHTREATMENTSHALLBEREGARDEDASTWOTREATMENTSFORWHICHSEPARATEFEESMAYBECHARGED.(ONLYAPPLICABLEIFSERVICESAREPROVIDEDBYASPECIALISTINPHYSICALMEDICINE)" },
                new MedicalItemPublication { Id = 39, MedicalItemId = 39, PublicationId = 2, Description = @"When a testis biopsy is done combined with vasogram or seminal vesiculogram or epididymogram, add 50% of the units for the appropriate procedure", NormalizedDescription = @"WHENATESTISBIOPSYISDONECOMBINEDWITHVASOGRAMORSEMINALVESICULOGRAMOREPIDIDYMOGRAM,ADD50%OFTHEUNITSFORTHEAPPROPRIATEPROCEDURE" },
                new MedicalItemPublication { Id = 40, MedicalItemId = 40, PublicationId = 2, Description = @"When a first consultation/visit proceeds into, or is immediately followed by a medical psychotherapeutic procedure, fees for the procedure are calculated according to the appropriate individual psychotherapy code (items 2957, 2974 or 2975)", NormalizedDescription = @"WHENAFIRSTCONSULTATION/VISITPROCEEDSINTO,ORISIMMEDIATELYFOLLOWEDBYAMEDICALPSYCHOTHERAPEUTICPROCEDURE,FEESFORTHEPROCEDUREARECALCULATEDACCORDINGTOTHEAPPROPRIATEINDIVIDUALPSYCHOTHERAPYCODE(ITEMS2957,2974OR2975)" },
                new MedicalItemPublication { Id = 41, MedicalItemId = 41, PublicationId = 2, Description = @"Multiple examinations: Full Fee", NormalizedDescription = @"MULTIPLEEXAMINATIONS:FULLFEE" },
                new MedicalItemPublication { Id = 42, MedicalItemId = 42, PublicationId = 2, Description = @"Repeat examinations: No reduction", NormalizedDescription = @"REPEATEXAMINATIONS:NOREDUCTION" },
                new MedicalItemPublication { Id = 43, MedicalItemId = 43, PublicationId = 2, Description = @""" + "" Means that this item is complementary to a preceding item and is therefore not subject to reduction", NormalizedDescription = @""" + ""MEANSTHATTHISITEMISCOMPLEMENTARYTOAPRECEDINGITEMANDISTHEREFORENOTSUBJECTTOREDUCTION" },
                new MedicalItemPublication { Id = 44, MedicalItemId = 44, PublicationId = 2, Description = @"A reduction of 33,33% (1/3) in the fee will apply to radiological examinations as indicated in section 19: Radiology where hospital equipment is used", NormalizedDescription = @"AREDUCTIONOF33,33%(1/3)INTHEFEEWILLAPPLYTORADIOLOGICALEXAMINATIONSASINDICATEDINSECTION19:RADIOLOGYWHEREHOSPITALEQUIPMENTISUSED" },
                new MedicalItemPublication { Id = 45, MedicalItemId = 45, PublicationId = 2, Description = @"Film costs: In the case of radiological items where films are used, practitioners should adjust the fee upwards or downwards in accordance with changes in the price of films in comparison with November 1979", NormalizedDescription = @"FILMCOSTS:INTHECASEOFRADIOLOGICALITEMSWHEREFILMSAREUSED,PRACTITIONERSSHOULDADJUSTTHEFEEUPWARDSORDOWNWARDSINACCORDANCEWITHCHANGESINTHEPRICEOFFILMSINCOMPARISONWITHNOVEMBER1979" },
                new MedicalItemPublication { Id = 46, MedicalItemId = 46, PublicationId = 2, Description = @"Left Side' modifier to be added to when items 6500 to 6519 are used when the left side is examined. Please note that the absence of this modifier indicates that the right side was examined", NormalizedDescription = @"LEFTSIDE'MODIFIERTOBEADDEDTOWHENITEMS6500TO6519AREUSEDWHENTHELEFTSIDEISEXAMINED.PLEASENOTETHATTHEABSENCEOFTHISMODIFIERINDICATESTHATTHERIGHTSIDEWASEXAMINED" },
                new MedicalItemPublication { Id = 47, MedicalItemId = 47, PublicationId = 2, Description = @"Vascular groups: ?Film series? and ?Introduction of Contrast Media? are complementary and together constitute a single examination: neither fee is therefore subject to increase in terms of Modifier 0080: Multiple examinations", NormalizedDescription = @"VASCULARGROUPS:?FILMSERIES?AND?INTRODUCTIONOFCONTRASTMEDIA?ARECOMPLEMENTARYANDTOGETHERCONSTITUTEASINGLEEXAMINATION:NEITHERFEEISTHEREFORESUBJECTTOINCREASEINTERMSOFMODIFIER0080:MULTIPLEEXAMINATIONS" },
                new MedicalItemPublication { Id = 48, MedicalItemId = 48, PublicationId = 2, Description = @"Radiologist?s fee for participation in a team: 30,00 radiology units per ? hour or part thereof for all interventional radiological procedures, excluding any pre- or post-operative angiography, catheterisation, CT-scanning, ultrasound-scanning or x-ray procedures. (Only to be charged if radiologist is hands-on, and not for interpretation of images only)", NormalizedDescription = @"RADIOLOGIST?SFEEFORPARTICIPATIONINATEAM:30,00RADIOLOGYUNITSPER?HOURORPARTTHEREOFFORALLINTERVENTIONALRADIOLOGICALPROCEDURES,EXCLUDINGANYPRE-ORPOST-OPERATIVEANGIOGRAPHY,CATHETERISATION,CT-SCANNING,ULTRASOUND-SCANNINGORX-RAYPROCEDURES.(ONLYTOBECHARGEDIFRADIOLOGISTISHANDS-ON,ANDNOTFORINTERPRETATIONOFIMAGESONLY)" },
                new MedicalItemPublication { Id = 49, MedicalItemId = 49, PublicationId = 2, Description = @"Diagnostic services rendered to hospital inpatients: Quote Modifier 0091 on all accounts for diagnostic services (e.g. MRI, X-rays, pathology tests) performed on patients officially admitted to hospital or day clinic (refer to Rule XX)", NormalizedDescription = @"DIAGNOSTICSERVICESRENDEREDTOHOSPITALINPATIENTS:QUOTEMODIFIER0091ONALLACCOUNTSFORDIAGNOSTICSERVICES(E.G.MRI,X-RAYS,PATHOLOGYTESTS)PERFORMEDONPATIENTSOFFICIALLYADMITTEDTOHOSPITALORDAYCLINIC(REFERTORULEXX)" },
                new MedicalItemPublication { Id = 50, MedicalItemId = 50, PublicationId = 2, Description = @"Diagnostic services rendered to outpatients: Quote Modifier 0092 on all accounts for diagnostic services (e.g. MRI, X-rays, pathology tests) performed on patients NOT officially admitted to hospital or day clinic (could be within the confines of a hospital) (refer to Rule YY)", NormalizedDescription = @"DIAGNOSTICSERVICESRENDEREDTOOUTPATIENTS:QUOTEMODIFIER0092ONALLACCOUNTSFORDIAGNOSTICSERVICES(E.G.MRI,X-RAYS,PATHOLOGYTESTS)PERFORMEDONPATIENTSNOTOFFICIALLYADMITTEDTOHOSPITALORDAYCLINIC(COULDBEWITHINTHECONFINESOFAHOSPITAL)(REFERTORULEYY)" },
                new MedicalItemPublication { Id = 51, MedicalItemId = 51, PublicationId = 2, Description = @"Radiation materials: Exclusively for use where radiation materials supplied by the practice are used by clinical and radiation oncologists, modifier 0095 should be used to identify these materials. A material code list with descriptions and guideline costs for these materials, maintained and updated on a regular basis, will be supplied  by the Society of Clinical and Radiation Oncology.  This modifier is only chargeable by the practice responsible for the cost of this material and where the hospital did not charge therefore. Please note that item 0201 should not be used for these materials", NormalizedDescription = @"RADIATIONMATERIALS:EXCLUSIVELYFORUSEWHERERADIATIONMATERIALSSUPPLIEDBYTHEPRACTICEAREUSEDBYCLINICALANDRADIATIONONCOLOGISTS,MODIFIER0095SHOULDBEUSEDTOIDENTIFYTHESEMATERIALS.AMATERIALCODELISTWITHDESCRIPTIONSANDGUIDELINECOSTSFORTHESEMATERIALS,MAINTAINEDANDUPDATEDONAREGULARBASIS,WILLBESUPPLIEDBYTHESOCIETYOFCLINICALANDRADIATIONONCOLOGY.THISMODIFIERISONLYCHARGEABLEBYTHEPRACTICERESPONSIBLEFORTHECOSTOFTHISMATERIALANDWHERETHEHOSPITALDIDNOTCHARGETHEREFORE.PLEASENOTETHATITEM0201SHOULDNOTBEUSEDFORTHESEMATERIALS" },
                new MedicalItemPublication { Id = 52, MedicalItemId = 52, PublicationId = 2, Description = @"Radio-isotope therapy patients who fail to keep their appointments: Fee will include cost of isotope", NormalizedDescription = @"RADIO-ISOTOPETHERAPYPATIENTSWHOFAILTOKEEPTHEIRAPPOINTMENTS:FEEWILLINCLUDECOSTOFISOTOPE" },
                new MedicalItemPublication { Id = 53, MedicalItemId = 53, PublicationId = 2, Description = @"Pathology tests performed by non-pathologists: Where items under Clinical Pathology (section 21) and Anatomical Pathology (section 22) fall within the province of other specialists or general practitioners, the fee is to be charged at two-thirds of the pathologists fee", NormalizedDescription = @"PATHOLOGYTESTSPERFORMEDBYNON-PATHOLOGISTS:WHEREITEMSUNDERCLINICALPATHOLOGY(SECTION21)ANDANATOMICALPATHOLOGY(SECTION22)FALLWITHINTHEPROVINCEOFOTHERSPECIALISTSORGENERALPRACTITIONERS,THEFEEISTOBECHARGEDATTWO-THIRDSOFTHEPATHOLOGISTSFEE" },
                new MedicalItemPublication { Id = 54, MedicalItemId = 54, PublicationId = 2, Description = @"Aspiration of biopsy procedure performed under direct ultrasound control by an ultrasound aspiration biopsy transducer (Static Realtime): Fee for part examined plus 30% of the units", NormalizedDescription = @"ASPIRATIONOFBIOPSYPROCEDUREPERFORMEDUNDERDIRECTULTRASOUNDCONTROLBYANULTRASOUNDASPIRATIONBIOPSYTRANSDUCER(STATICREALTIME):FEEFORPARTEXAMINEDPLUS30%OFTHEUNITS" },
                new MedicalItemPublication { Id = 55, MedicalItemId = 55, PublicationId = 2, Description = @"Use of contrast during ultrasound study: add 6.00 ultrasound units", NormalizedDescription = @"USEOFCONTRASTDURINGULTRASOUNDSTUDY:ADD6.00ULTRASOUNDUNITS" },
                new MedicalItemPublication { Id = 56, MedicalItemId = 56, PublicationId = 2, Description = @"Ultrasound in pregnancy, multiple gestation, after twenty weeks: plus 30%", NormalizedDescription = @"ULTRASOUNDINPREGNANCY,MULTIPLEGESTATION,AFTERTWENTYWEEKS:PLUS30%" },
                new MedicalItemPublication { Id = 57, MedicalItemId = 57, PublicationId = 2, Description = @"In order to charge the full fee (600,00 magnetic resonance units) for an examination of a specific single anatomical region, it should be performed with the applicable radio frequency coil including T1 and T2 weighted images on at least two planes", NormalizedDescription = @"INORDERTOCHARGETHEFULLFEE(600,00MAGNETICRESONANCEUNITS)FORANEXAMINATIONOFASPECIFICSINGLEANATOMICALREGION,ITSHOULDBEPERFORMEDWITHTHEAPPLICABLERADIOFREQUENCYCOILINCLUDINGT1ANDT2WEIGHTEDIMAGESONATLEASTTWOPLANES" },
                new MedicalItemPublication { Id = 58, MedicalItemId = 58, PublicationId = 2, Description = @"Where a limited series of a specific anatomical region is performed (except bone tumour), e.g. a T2 weighted image of a bone for an occult stress fracture, not more than two-thirds (2/3) of the fee may be charged. Also applicable to all radiotherapy planning studies, per region", NormalizedDescription = @"WHEREALIMITEDSERIESOFASPECIFICANATOMICALREGIONISPERFORMED(EXCEPTBONETUMOUR),E.G.AT2WEIGHTEDIMAGEOFABONEFORANOCCULTSTRESSFRACTURE,NOTMORETHANTWO-THIRDS(2/3)OFTHEFEEMAYBECHARGED.ALSOAPPLICABLETOALLRADIOTHERAPYPLANNINGSTUDIES,PERREGION" },
                new MedicalItemPublication { Id = 59, MedicalItemId = 59, PublicationId = 2, Description = @"All post-contrast studies (except bone tumour), including perfusion studies, to be charges at 50% of the fee", NormalizedDescription = @"ALLPOST-CONTRASTSTUDIES(EXCEPTBONETUMOUR),INCLUDINGPERFUSIONSTUDIES,TOBECHARGESAT50%OFTHEFEE" },
                new MedicalItemPublication { Id = 60, MedicalItemId = 60, PublicationId = 2, Description = @"Post-contrast study: Bone tumour: 100% of the fee", NormalizedDescription = @"POST-CONTRASTSTUDY:BONETUMOUR:100%OFTHEFEE" },
                new MedicalItemPublication { Id = 61, MedicalItemId = 61, PublicationId = 2, Description = @"Limited examination of the hypophysis e.g. where a coronal T1 and sagittal T1 series are performed, two-thirds (2/3) of the fee is applicable", NormalizedDescription = @"LIMITEDEXAMINATIONOFTHEHYPOPHYSISE.G.WHEREACORONALT1ANDSAGITTALT1SERIESAREPERFORMED,TWO-THIRDS(2/3)OFTHEFEEISAPPLICABLE" },
                new MedicalItemPublication { Id = 62, MedicalItemId = 62, PublicationId = 2, Description = @"Where, in a limited hypophysis examination, Gadolinium is administered and coronal T1 and sagittal T1 series are repeated, a single full fee for the entire examination is applicable + cost of Gadolinium + disposable items", NormalizedDescription = @"WHERE,INALIMITEDHYPOPHYSISEXAMINATION,GADOLINIUMISADMINISTEREDANDCORONALT1ANDSAGITTALT1SERIESAREREPEATED,ASINGLEFULLFEEFORTHEENTIREEXAMINATIONISAPPLICABLE+COSTOFGADOLINIUM+DISPOSABLEITEMS" },
                new MedicalItemPublication { Id = 63, MedicalItemId = 63, PublicationId = 2, Description = @"Where a magnetic resonance angiography (MRA) of large vessels is performed as primary examination, 100% of the fee is applicable. This modifier is only applicable if the series is performed by use of a recognised angiographic software package with reconstruction capability", NormalizedDescription = @"WHEREAMAGNETICRESONANCEANGIOGRAPHY(MRA)OFLARGEVESSELSISPERFORMEDASPRIMARYEXAMINATION,100%OFTHEFEEISAPPLICABLE.THISMODIFIERISONLYAPPLICABLEIFTHESERIESISPERFORMEDBYUSEOFARECOGNISEDANGIOGRAPHICSOFTWAREPACKAGEWITHRECONSTRUCTIONCAPABILITY" },
                new MedicalItemPublication { Id = 64, MedicalItemId = 64, PublicationId = 2, Description = @"Where a magnetic resonance angiography (MRA) of the vessels is performed additional to an examination of a particular region, 50% of the fee is applicable for the angiography. This modifier is only applicable if the series is performed by use of a recognised angiographic software package with reconstruction capability", NormalizedDescription = @"WHEREAMAGNETICRESONANCEANGIOGRAPHY(MRA)OFTHEVESSELSISPERFORMEDADDITIONALTOANEXAMINATIONOFAPARTICULARREGION,50%OFTHEFEEISAPPLICABLEFORTHEANGIOGRAPHY.THISMODIFIERISONLYAPPLICABLEIFTHESERIESISPERFORMEDBYUSEOFARECOGNISEDANGIOGRAPHICSOFTWAREPACKAGEWITHRECONSTRUCTIONCAPABILITY" },
                new MedicalItemPublication { Id = 65, MedicalItemId = 65, PublicationId = 2, Description = @"Where only a gradient echo series is performed with a machine without a recognised angiographic software package with reconstruction ability, 20% of the full fee is applicable specifying that it is a ?flow sensitive series?", NormalizedDescription = @"WHEREONLYAGRADIENTECHOSERIESISPERFORMEDWITHAMACHINEWITHOUTARECOGNISEDANGIOGRAPHICSOFTWAREPACKAGEWITHRECONSTRUCTIONABILITY,20%OFTHEFULLFEEISAPPLICABLESPECIFYINGTHATITISA?FLOWSENSITIVESERIES?" },
                new MedicalItemPublication { Id = 66, MedicalItemId = 66, PublicationId = 2, Description = @"Very limited studies to be charged at 33,33% of the full fee e.g. MR urography for renal colic, diffusion studies of the brain additional to routine brain", NormalizedDescription = @"VERYLIMITEDSTUDIESTOBECHARGEDAT33,33%OFTHEFULLFEEE.G.MRUROGRAPHYFORRENALCOLIC,DIFFUSIONSTUDIESOFTHEBRAINADDITIONALTOROUTINEBRAIN" },
                new MedicalItemPublication { Id = 67, MedicalItemId = 67, PublicationId = 2, Description = @"MRI spectroscopy: 50% of fee", NormalizedDescription = @"MRISPECTROSCOPY:50%OFFEE" },
                new MedicalItemPublication { Id = 68, MedicalItemId = 68, PublicationId = 2, Description = @"If a procedure lasts less than 30 minutes, only 50% of the machine fees for items 3536-3550 will be allowed (specify time of procedure on account)", NormalizedDescription = @"IFAPROCEDURELASTSLESSTHAN30MINUTES,ONLY50%OFTHEMACHINEFEESFORITEMS3536-3550WILLBEALLOWED(SPECIFYTIMEOFPROCEDUREONACCOUNT)" },
                new MedicalItemPublication { Id = 69, MedicalItemId = 69, PublicationId = 2, Description = @"If a procedure is performed by a radiologist in a facility not owned by himself, the fee will be reduced by 40% (i.e. 60% of the fee will be charged)", NormalizedDescription = @"IFAPROCEDUREISPERFORMEDBYARADIOLOGISTINAFACILITYNOTOWNEDBYHIMSELF,THEFEEWILLBEREDUCEDBY40%(I.E.60%OFTHEFEEWILLBECHARGED)" },
                new MedicalItemPublication { Id = 70, MedicalItemId = 70, PublicationId = 2, Description = @"When the procedure is performed by a non-radiologist, the fee will be reduced by 40% (i.e. 60% of the fee will be charged)", NormalizedDescription = @"WHENTHEPROCEDUREISPERFORMEDBYANON-RADIOLOGIST,THEFEEWILLBEREDUCEDBY40%(I.E.60%OFTHEFEEWILLBECHARGED)" },
                new MedicalItemPublication { Id = 71, MedicalItemId = 71, PublicationId = 2, Description = @"When a procedure is performed entirely by a non-radiologist in a facility owned by a radiologist, the radiologist owning the facility may charge 55% of the procedure units used. Modifier 6302 applies to the non radiologist performing the procedure", NormalizedDescription = @"WHENAPROCEDUREISPERFORMEDENTIRELYBYANON-RADIOLOGISTINAFACILITYOWNEDBYARADIOLOGIST,THERADIOLOGISTOWNINGTHEFACILITYMAYCHARGE55%OFTHEPROCEDUREUNITSUSED.MODIFIER6302APPLIESTOTHENONRADIOLOGISTPERFORMINGTHEPROCEDURE" },
                new MedicalItemPublication { Id = 72, MedicalItemId = 72, PublicationId = 2, Description = @"When multiple catheterisation procedures are used (items 3557, 3559, 3560, 3562) and an angiogram investigation is performed at each level, the unit value of each such multiple procedure will be reduced by 20,00 radiological units for each procedure after the initial catheterisation. The first catheterisation is charged at 100% of the unit value", NormalizedDescription = @"WHENMULTIPLECATHETERISATIONPROCEDURESAREUSED(ITEMS3557,3559,3560,3562)ANDANANGIOGRAMINVESTIGATIONISPERFORMEDATEACHLEVEL,THEUNITVALUEOFEACHSUCHMULTIPLEPROCEDUREWILLBEREDUCEDBY20,00RADIOLOGICALUNITSFOREACHPROCEDUREAFTERTHEINITIALCATHETERISATION.THEFIRSTCATHETERISATIONISCHARGEDAT100%OFTHEUNITVALUE" }
            );
        }
    }
}