using MedicalEngineMicroService.Common.Extensions;
using MedicalEngineMicroService.Core.Models.Entities.Medical;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MedicalEngineMicroService.Persistence.EntityConfigurations.Medical {
    public class PractitionerPractitionerTypeConfiguration : IEntityTypeConfiguration<PractitionerPractitionerType> {
        public void Configure (EntityTypeBuilder<PractitionerPractitionerType> builder) {
            builder.ConfigureEntity ();
            SeedPractitionerPratitionerType(builder);
        }

        private void SeedPractitionerPratitionerType (EntityTypeBuilder<PractitionerPractitionerType> modelBuilder) {
            modelBuilder.HasData (
                new PractitionerPractitionerType { Id = 1, PractitionerId = 4, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 2, PractitionerId = 4, PractitionerTypeId = 5 },
                new PractitionerPractitionerType { Id = 3, PractitionerId = 5, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 4, PractitionerId = 6, PractitionerTypeId = 3 },
                new PractitionerPractitionerType { Id = 5, PractitionerId = 7, PractitionerTypeId = 6 },
                new PractitionerPractitionerType { Id = 6, PractitionerId = 8, PractitionerTypeId = 6 },
                new PractitionerPractitionerType { Id = 7, PractitionerId = 9, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 8, PractitionerId = 10, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 9, PractitionerId = 11, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 10, PractitionerId = 12, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 11, PractitionerId = 13, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 12, PractitionerId = 14, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 13, PractitionerId = 15, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 14, PractitionerId = 16, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 15, PractitionerId = 18, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 16, PractitionerId = 19, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 17, PractitionerId = 20, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 18, PractitionerId = 21, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 19, PractitionerId = 22, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 20, PractitionerId = 23, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 21, PractitionerId = 24, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 22, PractitionerId = 25, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 23, PractitionerId = 26, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 24, PractitionerId = 27, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 25, PractitionerId = 28, PractitionerTypeId = 2 },
                new PractitionerPractitionerType { Id = 26, PractitionerId = 29, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 27, PractitionerId = 30, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 28, PractitionerId = 31, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 29, PractitionerId = 33, PractitionerTypeId = 2 },
                new PractitionerPractitionerType { Id = 30, PractitionerId = 34, PractitionerTypeId = 2 },
                new PractitionerPractitionerType { Id = 31, PractitionerId = 42, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 32, PractitionerId = 43, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 33, PractitionerId = 51, PractitionerTypeId = 2 },
                new PractitionerPractitionerType { Id = 34, PractitionerId = 52, PractitionerTypeId = 2 },
                new PractitionerPractitionerType { Id = 35, PractitionerId = 54, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 36, PractitionerId = 55, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 37, PractitionerId = 56, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 38, PractitionerId = 57, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 39, PractitionerId = 58, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 40, PractitionerId = 59, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 41, PractitionerId = 60, PractitionerTypeId = 2 },
                new PractitionerPractitionerType { Id = 42, PractitionerId = 61, PractitionerTypeId = 3 },
                new PractitionerPractitionerType { Id = 43, PractitionerId = 62, PractitionerTypeId = 3 },
                new PractitionerPractitionerType { Id = 44, PractitionerId = 63, PractitionerTypeId = 2 },
                new PractitionerPractitionerType { Id = 45, PractitionerId = 69, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 46, PractitionerId = 72, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 47, PractitionerId = 73, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 48, PractitionerId = 79, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 49, PractitionerId = 84, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 50, PractitionerId = 85, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 51, PractitionerId = 86, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 52, PractitionerId = 87, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 53, PractitionerId = 88, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 54, PractitionerId = 89, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 55, PractitionerId = 90, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 56, PractitionerId = 91, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 57, PractitionerId = 92, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 58, PractitionerId = 93, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 59, PractitionerId = 94, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 60, PractitionerId = 95, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 61, PractitionerId = 96, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 62, PractitionerId = 97, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 63, PractitionerId = 98, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 64, PractitionerId = 99, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 65, PractitionerId = 100, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 66, PractitionerId = 101, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 67, PractitionerId = 102, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 68, PractitionerId = 103, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 69, PractitionerId = 104, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 70, PractitionerId = 128, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 71, PractitionerId = 129, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 72, PractitionerId = 130, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 73, PractitionerId = 131, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 74, PractitionerId = 132, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 75, PractitionerId = 133, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 76, PractitionerId = 134, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 77, PractitionerId = 135, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 78, PractitionerId = 136, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 79, PractitionerId = 137, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 80, PractitionerId = 138, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 81, PractitionerId = 139, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 82, PractitionerId = 140, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 83, PractitionerId = 141, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 84, PractitionerId = 142, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 85, PractitionerId = 143, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 86, PractitionerId = 150, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 87, PractitionerId = 151, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 88, PractitionerId = 152, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 89, PractitionerId = 154, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 90, PractitionerId = 160, PractitionerTypeId = 2 },
                new PractitionerPractitionerType { Id = 91, PractitionerId = 161, PractitionerTypeId = 2 },
                new PractitionerPractitionerType { Id = 92, PractitionerId = 163, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 93, PractitionerId = 176, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 94, PractitionerId = 178, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 95, PractitionerId = 184, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 96, PractitionerId = 188, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 97, PractitionerId = 189, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 98, PractitionerId = 190, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 99, PractitionerId = 192, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 100, PractitionerId = 193, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 101, PractitionerId = 194, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 102, PractitionerId = 195, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 103, PractitionerId = 196, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 104, PractitionerId = 197, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 105, PractitionerId = 198, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 106, PractitionerId = 199, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 107, PractitionerId = 200, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 108, PractitionerId = 214, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 109, PractitionerId = 215, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 110, PractitionerId = 216, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 111, PractitionerId = 217, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 112, PractitionerId = 218, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 113, PractitionerId = 219, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 114, PractitionerId = 220, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 115, PractitionerId = 221, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 116, PractitionerId = 222, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 117, PractitionerId = 223, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 118, PractitionerId = 224, PractitionerTypeId = 6 },
                new PractitionerPractitionerType { Id = 119, PractitionerId = 225, PractitionerTypeId = 3 },
                new PractitionerPractitionerType { Id = 120, PractitionerId = 226, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 121, PractitionerId = 227, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 122, PractitionerId = 228, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 123, PractitionerId = 229, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 124, PractitionerId = 230, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 125, PractitionerId = 231, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 126, PractitionerId = 232, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 127, PractitionerId = 233, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 128, PractitionerId = 234, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 129, PractitionerId = 235, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 130, PractitionerId = 236, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 131, PractitionerId = 239, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 132, PractitionerId = 240, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 133, PractitionerId = 243, PractitionerTypeId = 1 },
                new PractitionerPractitionerType { Id = 134, PractitionerId = 246, PractitionerTypeId = 3 },
                new PractitionerPractitionerType { Id = 135, PractitionerId = 248, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 136, PractitionerId = 249, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 137, PractitionerId = 250, PractitionerTypeId = 4 },
                new PractitionerPractitionerType { Id = 138, PractitionerId = 251, PractitionerTypeId = 4 }
            );
        }
    }
}